routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => 'auth'], function () { // Authenticated Users Only
	// users resource
	Route::resource('user', 'userController');
	// sections resources
	Route::resource('section', 'sectionController');
	// route for re-sorting the sections grid
	Route::post('section/sort', ['uses' => 'sectionController@sortSections', 'as' => 'section.sort']);
	// route to toogle section status
	Route::post('section/switch', ['uses' => 'sectionController@switchSections', 'as' => 'section.switch']);

	Route::get('/crawler', 'crawlerController@index')->name('crawler');

});

// Authentication routes...
Route::get('/logout', ['uses' => 'Auth\LoginController@logout', 'as' => 'logout']);

app/section.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class section extends Model
{
	use SoftDeletes;

    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'section';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['title', 'content', 'type', 'status', 'image'];

    public function getImageUrlAttribute(){
        return '/'. trim($this->image, '/');
    }
}

app/Http/Controllers/sectionController.php
<?php
namespace App\Http\Controllers;

use File;
use Session;
use Validator;
use App\section;
use Illuminate\Http\Request;

/**
 * Class sectionController
 * Section controller class to manage the resources of section routes
 *
 * @author Mahmoud Mostaf <jinkazama_m@yahoo.com>
 */

class sectionController extends Controller
{
    private $status;
    
    private $uploadTo;

    public function __construct()
    {

        view()->share('currentController', 'Sections');
        
        $this->status = ['Inactive', 'Active'];

        $this->uploadTo = 'uploads';
    }

    /**
     * List Suppliers
     * Display a listing of the Suppliers from the database table "section" with pagination.
     *
     * @return Response
     */
    public function index()
    {
        $section = section::orderBy('section_order')->get();
        
        return view('section.index', ['section' => $section, 'status' => $this->status]);
    }

    /**
     * Create New Section Form
     * Show the HTML form for creating a new Section in the database table "section".
     *
     * @return Response
     */
    public function create()
    {

       return view('section.create', ['status' => $this->status]);
   }

    /**
     * Insert New Section
     * Actual Store a newly created section in database table "section".
     *
     * @return Response
     */
    public function store(Request $request)
    {

        if($this->is_valid($request , $v) === false){
            return redirect('section/create')
            ->withErrors($v)
            ->withInput();
        }
        
        $input = $request->all();

        if (request()->hasFile('image')) {
            $image = request()->file('image');

            $name = time().'.'.$image->getClientOriginalExtension();
            $directory = $this->uploadTo;
            
            $destinationPath = public_path($directory);
            $image->move($destinationPath, $name);
            
            $input['image'] = $directory.'/'.$name;
        }

        section::create($input);

        Session::flash('message', 'Section added successfully !');

        return redirect('section');
    }

    /**
     * Show Section Data
     * Display the specified Section and all of his information.
     *
     * @param  int  $id
     *
     * @return Response
     */
    public function show($id)
    {
        $section = section::findOrFail($id);

        return view('section.show', ['section' => $section, 'status' => $this->status]);
    }

    /**
     * Edit One section
     * Show the HTML form for editing the specified section.
     *
     * @param  int  $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $section = section::findOrFail($id);

        return view('section.edit', ['section' => $section, 'status' => $this->status]);
    }

    /**
     * Update section Data
     * Actual Update the specified section Data in database table "section".
     *
     * @param  int  $id
     *
     * @return Response
     */
    public function update($id, Request $request)
    {

        if($this->is_valid($request , $v, $id) === false){
            return redirect('section/'. $id .'/edit')
            ->withErrors($v)
            ->withInput();
        }
        
        $section = section::findOrFail($id);

        $input = $request->all();

        if (request()->hasFile('image')) {

            $directory = $this->uploadTo;

            $old_full_image = public_path($directory.'/'.$section->image);

            if (file_exists($old_full_image)) {
                File::delete($old_full_image);
            }

            $image = request()->file('image');

            $name = time().'.'.$image->getClientOriginalExtension();
            
            $destinationPath = public_path($directory);
            $image->move($destinationPath, $name);
            
            $input['image'] = $directory.'/'.$name;
        }

        $section->update($input);

        Session::flash('message', 'Section updated successfully !');

        return redirect('section');
    }

    /**
     * Delete One section Row
     * Remove the specified Row section from the Database table "section".
     *
     * @param  int  $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        section::destroy($id);

        Session::flash('message', 'section deleted!');

        return redirect('section');
    }
    
    /**
     * Validate Parameters
     * Actual Validate The Incoming Request Parameters.
     *
     * @return Boolean
     */
    public function is_valid($request , &$v, $id=null)
    {
        $input = $request->all();
        
        if(isset($input['_method']) && $input['_method'] == 'PATCH'){

            $v = Validator::make($request->all(), [
                'title' => 'required|string|min:2',
                'type' => 'required|string|min:2|unique:section,type,' . $id,
                'content' => 'required|string|min:2',
                'image' => 'sometimes|image|mimes:jpeg,png,jpg,gif,svg|max:2048',
                'status' => 'required'
                ]);

        } else {

            $v = Validator::make($request->all(), [
                'title' => 'required|string|min:2',
                'type' => 'required|string|min:2|unique:section',
                'content' => 'required|string|min:2',
                'image' => 'sometimes|image|mimes:jpeg,png,jpg,gif,svg|max:2048',
                'status' => 'required'
                ]);
        }

        return $v->fails() ? false : true;
        
    }

    /**
     * Sort sections
     * Sort the selected section from the grid by id
     *
     * @return Response JSON
     */
    public function sortSections()
    {

        $input = request()->all();

        $saved = 0;

        foreach ($input['sort'] as $key => $id) {

            $section = section::findOrFail($id);
            $section->section_order = $key;

            if ($section->save()) {
                $saved++;
            }
        }

        if ($saved == count($input['sort'])) {
            return response()->json(['status' => 'success']);
        } else {
            return response()->json(['status' => 'failed']);
        }
    }

    /**
     * Toggle sections status
     * Toggle sections grid to switch status
     *
     * @return Response JSON
     */
    public function switchSections()
    {
        $input = request()->all();
        
        $id = $input['id'];
        
        $state = $input['state'] ? 1 : 0;
        
        $section = section::findOrFail($id);
        
        $section->status = $state;

        if ($section->save()) {
             return response()->json(['status' => 'success']);
        } else {
            return response()->json(['status' => 'failed']);
        }
        
    }
    
}

resources/views/section/create.blade.php
@extends('layouts.default')

@push('js')
    <link href="{{ asset('layout/assets/WYSIWYG-Editor/Editor.css') }}" rel="stylesheet" type="text/css">
@endpush

@section('content')


<!-- Contextual classes -->
<div class="panel panel-flat">

    <div class="panel-heading">
        <h5>Create New Section</h5>
    </div>

    <div class="panel-body">
        Creating new Section for the homepage layout.

        <hr>

        @include('layouts._errors')

        {!! Form::open(['url' => 'section', 'class' => 'form-horizontal', 'files' => true]) !!}

            <div class="form-group {{ $errors->has('title') ? 'has-error' : ''}}">
                {!! Form::label('title', 'Title: ', ['class' => 'col-sm-3 control-label fa  fa-flash']) !!}
                <div class="col-sm-12">
                    {!! Form::text('title', null, ['class' => 'form-control']) !!}
                    {!! $errors->first('title', '<p class="help-block">:message</p>') !!}
                </div>
            </div>

            <div class="form-group {{ $errors->has('type') ? 'has-error' : ''}}">
                {!! Form::label('type', ' Type: ', ['class' => 'col-sm-3 control-label fa  fa-flash']) !!}
                <div class="col-sm-12">
                    {!! Form::text('type', null, ['class' => 'form-control']) !!}
                    {!! $errors->first('type', '<p class="help-block">:message</p>') !!}
                </div>
            </div>

            <div class="form-group {{ $errors->has('section_order') ? 'has-error' : ''}}">
                {!! Form::label('section_order', ' Section order (index): ', ['class' => 'col-sm-3 control-label fa  fa-flash']) !!}
                <div class="col-sm-12">
                    {!! Form::text('section_order', null, ['class' => 'form-control']) !!}
                    {!! $errors->first('section_order', '<p class="help-block">:message</p>') !!}
                </div>
            </div>

            <div class="form-group {{ $errors->has('content') ? 'has-error' : ''}}">
                {!! Form::label('content', ' Content: ', ['class' => 'col-sm-3 control-label']) !!}
                <div class="col-sm-12">
                    {!! Form::textarea('content', null, ['class' => 'form-control ckeditor']) !!}
                    {!! $errors->first('content', '<p class="help-block">:message</p>') !!}
                </div>
            </div>
            
            <div class="form-group {{ $errors->has('status') ? 'has-error' : ''}}">
                {!! Form::label('status', ' Status: ', ['class' => 'col-sm-3 control-label fa  fa-flash']) !!}
                <div class="col-sm-12">
                    {!! Form::select('status', $status, 1, ['class' => 'form-control']) !!}
                    {!! $errors->first('status', '<p class="help-block">:message</p>') !!}
                </div>
            </div>

            <div class="form-group {{ $errors->has('image') ? 'has-error' : ''}}">
                {!! Form::label('image', ' Image: ', ['class' => 'col-sm-3 control-label ']) !!}
                <div class="col-sm-12">
                    <input name="image" accept="image/x-png,image/gif,image/jpeg" type="file" class="upload">
                    {!! $errors->first('image', '<p class="help-block">:message</p>') !!}
                </div>
            </div>
            
            
    <div class="form-group">
        <div class="col-sm-offset-3 col-sm-3">
            {!! Form::submit('Create', ['class' => 'btn btn-primary form-control']) !!}
        </div>
    </div>
    {!! Form::close() !!}

    </div>
</div>
<!-- /contextual classes -->


@endsection

@push('js')
    <script type="text/javascript" src="{{ asset('layout/assets/ckeditor/ckeditor.js') }}"></script>
@endpush

resources/views/section/edit.blade.php
@extends('layouts.default')

@section('content')


<!-- Contextual classes -->
<div class="panel panel-flat">

    <div class="panel-heading">
        <h5>Edit section</h5>
    </div>

    <div class="panel-body">
        Editing the section data.

        <hr>

        @include('layouts._errors')

        {!! Form::model($section, [
            'method' => 'PATCH',
            'url' => ['section', $section->id],
            'class' => 'form-horizontal',
            'files' => true
        ]) !!}

            <div class="form-group {{ $errors->has('title') ? 'has-error' : ''}}">
                {!! Form::label('title', 'Title: ', ['class' => 'col-sm-3 control-label fa  fa-flash']) !!}
                <div class="col-sm-12">
                    {!! Form::text('title', null, ['class' => 'form-control']) !!}
                    {!! $errors->first('title', '<p class="help-block">:message</p>') !!}
                </div>
            </div>

            <div class="form-group {{ $errors->has('type') ? 'has-error' : ''}}">
                {!! Form::label('type', ' Type: ', ['class' => 'col-sm-3 control-label fa  fa-flash']) !!}
                <div class="col-sm-12">
                    {!! Form::text('type', null, ['class' => 'form-control']) !!}
                    {!! $errors->first('type', '<p class="help-block">:message</p>') !!}
                </div>
            </div>

            <div class="form-group {{ $errors->has('section_order') ? 'has-error' : ''}}">
                {!! Form::label('section_order', ' Section order (index): ', ['class' => 'col-sm-3 control-label fa  fa-flash']) !!}
                <div class="col-sm-12">
                    {!! Form::text('section_order', null, ['class' => 'form-control']) !!}
                    {!! $errors->first('section_order', '<p class="help-block">:message</p>') !!}
                </div>
            </div>

            <div class="form-group {{ $errors->has('content') ? 'has-error' : ''}}">
                {!! Form::label('content', ' Content: ', ['class' => 'col-sm-3 control-label']) !!}
                <div class="col-sm-12">
                    {!! Form::textarea('content', $section->content, ['class' => 'form-control ckeditor']) !!}
                    {!! $errors->first('content', '<p class="help-block">:message</p>') !!}
                </div>
            </div>
            
            <div class="form-group {{ $errors->has('status') ? 'has-error' : ''}}">
                {!! Form::label('status', ' Status: ', ['class' => 'col-sm-3 control-label fa  fa-flash']) !!}
                <div class="col-sm-12">
                    {!! Form::select('status', $status, 1, ['class' => 'form-control']) !!}
                    {!! $errors->first('status', '<p class="help-block">:message</p>') !!}
                </div>
            </div>

            <div class="form-group {{ $errors->has('image') ? 'has-error' : ''}}">
                {!! Form::label('image', ' Image: ', ['class' => 'col-sm-3 control-label ']) !!}
                <div class="col-sm-12">
                    <img width="50%" src="{{ $section->image_url }}" />
                </div>
            </div>

            <div class="form-group {{ $errors->has('image') ? 'has-error' : ''}}">
                {!! Form::label('image', 'Replace Image: ', ['class' => 'col-sm-3 control-label ']) !!}
                <div class="col-sm-12">
                    <input name="image" accept="image/x-png,image/gif,image/jpeg" type="file" class="upload">
                    {!! $errors->first('image', '<p class="help-block">:message</p>') !!}
                </div>
            </div>


    <div class="form-group">
        <div class="col-sm-offset-3 col-sm-3">
            {!! Form::submit('Update', ['class' => 'btn btn-primary form-control']) !!}
        </div>
    </div>
    {!! Form::close() !!}

    </div>
</div>
<!-- /contextual classes -->


@endsection

@push('js')
    <script type="text/javascript" src="{{ asset('layout/assets/ckeditor/ckeditor.js') }}"></script>
@endpush

resources/views/section/index.blade.php
@extends('layouts.default')

@push('css')
<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/smoothness/jquery-ui.css">
<link rel="stylesheet" href="{{ asset('layout/assets/bootstrap-switch-master/docs/css/highlight.css') }}">
<link rel="stylesheet" href="{{ asset('layout/assets/bootstrap-switch-master/dist/css/bootstrap3/bootstrap-switch.css') }}">
<style>tr.ttr{transition: ease-in .3s;} tr.disabled{opacity: .3}</style>
@endpush

@section('content')


@if(Session::has('message'))

<div class="alert alert-success alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
    {{ ucwords(Session::get('message')) }} 
</div>
@endif  


<!-- Contextual classes -->
<div class="panel panel-flat">
    <div class="panel-heading">
        <h5>Sections List <a href="{{ url('section/create') }}" class="btn btn-primary pull-right btn-sm">Add New Section</a></h5>
    </div>

    <div class="panel-body">
        List of all the sections. You can start drag to sort them


        <div class="table">
            <table class="table table-striped table-hover ">
                <thead>
                    <tr>
                        <th>ID</th><th>Title</th><th>Status</th><th>Last updated</th><th width="170px">Actions</th>
                    </tr>
                </thead>
                <tbody id="sorted_table" class="sorted_table connectedSortable">
                    @php $x=0; @endphp

                    @foreach($section as $item)

                    @php $x++; @endphp

                    <tr id="{{ $item->id }}" class="ttr @if(!$item->status) disabled @endif">
                        <td>{{ $item->id }}</td>
                        <td>
                            <a href="{{ url('section/' .  $item->id . '/edit') }}">{{ $item->title }}</a>
                        </td>
                        <td>{{ $status[$item->status] }}</td>
                        <td>{{ $item->updated_at }}</td>
                        <td>
                            <a href="{{ url('section/' . $item->id . '/edit') }}">
                                <button type="submit" class="btn btn-primary btn-xs">Update</button>
                            </a> 
                            /
                            <input class="switch-state" data-id="{{ $item->id }}" size="mini" type="checkbox" @if($item->status == 1) checked @endif>
                            /
                            {!! Form::open([
                            'method'=>'DELETE',
                            'url' => ['section', $item->id],

                            'style' => 'display:inline',
                            'name' => 'delete_' . $item->id,
                            'class' => 'deleteForm',
                            ]) !!}
                            {!! Form::submit('Delete', ['class' => 'btn btn-danger btn-xs delete',  'data-toggle' => 'modal', 'data-target' => '#confirmDelete', 'data-title' => 'Delete section', 'data-message' => 'Are you sure you want to delete this section ?', 'rel' => $item->id]) !!}
                            {!! Form::close() !!}

                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
            
        </div>
    </div>
</div>
<!-- /contextual classes -->


@include('layouts.deleteConfirm')

@endsection

@push('js')

<script src="//code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script src="{{ asset('layout/assets/bootstrap-switch-master/dist/js/bootstrap-switch.js') }}"></script>
<script type="text/javascript">

    $(".sorted_table").sortable({update: function(event, ui){
        var data = $(this).sortable("toArray");

        $.ajax({
            data: {"sort": data, "_token": "{{ csrf_token() }}"},
            type: 'POST',
            url: "{{ route('section.sort') }}"
        });
    }});


    $(document).ready(function () {

        $('.switch-state').bootstrapSwitch();
        $('.switch-state').on('switchChange.bootstrapSwitch', function (event, state) {
         var here = $(this);
         var id = $(this).data('id');

         var start = $.post("{{ route('section.switch') }}", {state: state, id: id, '_token': $('input[name=_token]').val()});
         start.done(function (data) {
            if (data.status == "success") {
                if(!state){
                    here.closest("tr").addClass("disabled");
                }else{
                    here.closest("tr").removeClass("disabled");
                }
            } else {
                alert("Something went wrong, please try again");
            }
        });
     });

    });

</script>

@endpush